version: '3'

services:

### PHP-CLI Container #######################################

    php71-cli-service:
      container_name: "php-${TAG_PHP71_CLI}"
      image: "yann/php:${TAG_PHP71_CLI}"
      build:
        context: ./build
        dockerfile: docker_file_php71_cli
        args:
          - IMAGE_TAG=${TAG_PHP71_CLI}
          - WITH_XDEBUG=${PHP_WITH_XDEBUG} 
          - WITH_COMPOSER=${PHP_WITH_COMPOSER}
      volumes:
        - ${PATH_PROJECT_ROOT}/conf/php.ini:/usr/local/etc/php/php.ini
        - ${PATH_PROJECT_ROOT}/conf/php_xdbug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdbug.ini
        - ${PATH_WEB_DATA}/php_log:/usr/local/var/log
        - ${PATH_WEB_TEST}:/var/www/test
      working_dir: /var/www/test
      networks:
        - php-cli
      ports:
        - "8000:8000"
      environment:
        TZ: "Asia/Shanghai"
        HOSTNAME: xdebug_ide_host
      extra_hosts:
        xdebug_ide_host: ${XDEBUG_IDE_HOST_IP}

### Networks Setup ##########################################

networks:
    php-cli:
